### ISSUE TITLE
add a landing page

### ISSUE THREAD

**Issue by OlivierJM** [SparkEdUAB/sparked-client#11]

**Comment by OlivierJM** [comment]
https://react-rainbow.web.app

**Comment by OlivierJM** [comment]
@YoramGondwe any progress with this one ?

**Comment by YoramGondwe** [comment]
I am having some issues implementing the VerticalSectionOverflow from react-rainbow

**Comment by OlivierJM** [comment]
ahhh I see send in a PR then we can discuss from there

**Comment by OlivierJM** [comment]
I am closing this issue, it was fixed #42
