### ISSUE TITLE
update readme 

### ISSUE THREAD

**Issue by OlivierJM** [SparkEdUAB/sparked-client#24]
Add more information in the readme to reflect instructions and other related information

**Comment by OlivierJM** [comment]
a good example would be what is here https://github.com/SparkEdUAB/sparked-server

**Comment by OlivierJM** [comment]
What is needed in the readme

- Summary of the project, can be found [here](https://sparkeduab.github.io/sparked-manual) 
- What's required to run the project and the tech stack used
- Instructions on how to run the project
- Contributing guide
- Code of Conduct

**Comment by WillzMu** [comment]
we might need to update this one soon to let other possible contributors be able to run the project. I am guessing the SparkEd client needs the SparkEd server to run?

**Comment by OlivierJM** [comment]
Yeahh very true, I might jump on it tomorrow morning

**Comment by OlivierJM** [comment]
If its of interest to add to the readme the current looks of the minimal dashboard
![Screenshot 2019-10-06 at 12 40 02 AM](https://user-images.githubusercontent.com/11255454/66261676-1dc35600-e7d2-11e9-8a7a-b1a0e29f5160.png)

**Comment by OlivierJM** [comment]
I have added the basics in the readme, I think I will close this issue soon if there isn't update.
