### ISSUE TITLE
update page title

### ISSUE THREAD

**Issue by WillzMu** [SparkEdUAB/sparked-client#30]
current page title says 'React App' . Might want to update it to the name of the project

**Comment by OlivierJM** [comment]
Ohh yeah thanks so much for this Willz, wanna send in a PR ?

**Comment by WillzMu** [comment]
minor one but will take it. Got any other juicy stuff hehe

**Comment by OlivierJM** [comment]
Yeahh more stuff will be coming soon, https://github.com/SparkEdUAB/sparked-server has more cool stuff but I am loving GraphQL on the front-end too.
I just need to get the release pipeline properly deploying so that data can be accessible in production, that will happen soon.
Thanks for the PR 💪🏾
