### ISSUE TITLE
state management

### ISSUE THREAD

**Issue by OlivierJM** [SparkEdUAB/sparked-client#32]
This is one of those things they say just like the basic state, you will know that you need it when you need it.
At the moment we don't need global state, we will try and keep the state as close as possible to the components that own the state, but in some instance, we might need to start using global state.

e.g: i18n(Localization), Theming(Dark & Light mode)

There are other use cases that will come along the way and once we get there ofcourse we will know how to deal with such cases.

There are different libs for managing state but from my own experience and research that I have done, the choice comes down to few options:

- `React Context API` with hooks
- <del>Apollo client(currently used for `GraphQL` queries)</del>
- `MobX` 

Ideas and discussion on this are very welcome

**Comment by OlivierJM** [comment]
suggest we go with hooks for now.

**Comment by YoramGondwe** [comment]
I agree using hooks is a very efficient way of managing state that's not too complicated to handle and maintain

**Comment by OlivierJM** [comment]
Yep it works just fine. 
closing this for now.
