### ISSUE TITLE
React router not refreshing after route change[BUG]

### ISSUE THREAD

**Issue by OlivierJM** [SparkEdUAB/sparked-client#44]
**Describe the bug**
When a new url is changed in the browser url, react router first shows a 404 page within a wrapper.

**To Reproduce**
1. Go to '/'
2. Click on 'Get Started'
3. Log in
4. Click on SparkEd in the header
5. It shows a 404 page inside a client wrapper

**Expected behavior**
It should take you to the landing page without a full page reload

**Additional context**
The issue has to do with the way routes are organized and maybe we could try code splitting.

**Comment by WillzMu** [comment]
Hey @OlivierJM can I claim this one

**Comment by OlivierJM** [comment]
Yes please go ahead, 
To best try this put this `REACT_APP_SERVER_ADDRESS="http://46.101.133.8"` in your .env file to get access to the server  so that you can login then try and navigate through other routes.
The routes that are causing issues are `/` and '/login' and `*` not found pages
My suspicion is the route arrangement because of admin and client.

If you don't manage to log in, let me know I can help set up [this server](https://github.com/SparkEdUAB/sparked-client)
